from game import *

pika = Pokemon("Pikachu", random.randint(80,120), Type.Electric)
Vive_Attaque = Attack("Vive_Attaque", 5, 25, Type.Normal)
pika.add_attack(Vive_Attaque)
Charme = Attack("Charme", 5, 25, Type.Normal)
pika.add_attack(Charme)
Tonnerre = Attack("Tonnerre", 20, 15, Type.Electric)
pika.add_attack(Tonnerre)
Fatal_Foudre = Attack("Fatal_Foudre", 80, 5, Type.Electric)
pika.add_attack(Fatal_Foudre)

menta = Pokemon("Mentali", random.randint(80,120), Type.Psy)
Météores = Attack("Météores", 20, 10, Type.Rock)
menta.add_attack(Météores)
Protection = Attack("Protection", 0, 5, Type.Buff, True)
menta.add_attack(Protection)
Coud_Boue = Attack("Coud'Boue", 5, 25, Type.Rock)
menta.add_attack(Coud_Boue)
Psyko = Attack("Psyko", 50, 10, Type.Psy)
menta.add_attack(Psyko)

ronfl = Pokemon("Ronflex", random.randint(80,120), Type.Normal)
Plaquage = Attack("Plaquage", 40, 15, Type.Normal)
ronfl.add_attack(Plaquage)
Repos = Attack("Repos", 0, 5, Type.Buff, True)
ronfl.add_attack(Repos)
Ronflement = Attack("Ronflement", 20, 15, Type.Normal)
ronfl.add_attack(Ronflement)
Amnesie = Attack("Amnesie", 75, 5, Type.Psy)
ronfl.add_attack(Amnesie)

flori = Pokemon("Florizarre", random.randint(80,120), Type.Grass)
Giga_Sangsue = Attack("Giga_Sangsue", 70, 10, Type.Grass)
flori.add_attack(Giga_Sangsue)
Zenith = Attack("Zenith", 5, 25, Type.Grass)
flori.add_attack(Zenith)
Synthese = Attack("Synthese", 5, 15, Type.Grass)
flori.add_attack(Synthese)
Lance_Soleil = Attack("Lance_Soleil", 65, 10, Type.Grass)
flori.add_attack(Lance_Soleil)

dracau = Pokemon("Dracaufeu", random.randint(80,120), Type.Fire)
Cru_Aile = Attack("Cru_Aile", 5, 25, Type.Flying)
dracau.add_attack(Cru_Aile)
Danseflamme = Attack("Danseflamme", 0, 5, Type.Buff, True)
dracau.add_attack(Danseflamme)
Tranche = Attack("Tranche", 20, 15, Type.Fire)
dracau.add_attack(Tranche)
Lance_Flamme = Attack("Lance-Flamme", 45, 10, Type.Fire)
dracau.add_attack(Lance_Flamme)

tort = Pokemon("Tortank", random.randint(80,120), Type.Water)
Surf = Attack("Surf", 35, 20, Type.Water)
tort.add_attack(Surf)
Danse_Pluie = Attack("Danse Pluie", 0, 5, Type.Buff, True)
tort.add_attack(Danse_Pluie)
Blizzard = Attack("Blizzard", 15, 20, Type.Water)
tort.add_attack(Blizzard)
Siphon = Attack("Siphon", 10, 20, Type.Water)
tort.add_attack(Siphon)

#////////////////////////////////////////////////////////////////////////BLUE\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

rouc = Pokemon("Roucarnage", random.randint(80,120), Type.Flying)
rouc.add_attack(Vive_Attaque)
Cyclone = Attack("Cyclone", 20, 15, Type.Flying)
rouc.add_attack(Cyclone)
rouc.add_attack(Cru_Aile)
Mimique = Attack("Mimique", 5, 25, Type.Normal)
rouc.add_attack(Mimique)

koko = Pokemon("Noadkoko", random.randint(80,120), Type.Grass)
koko.add_attack(Zenith)
koko.add_attack(Giga_Sangsue)
BombOeuf = Attack("BombOeuf", 15, 25, Type.Grass)
koko.add_attack(BombOeuf)
koko.add_attack(Lance_Soleil)

arca = Pokemon("Arcanin", random.randint(80,120), Type.Fire)
Hurlement = Attack("Hurlement", 10, 15, Type.Normal)
arca.add_attack(Hurlement)
arca.add_attack(Météores)
arca.add_attack(Lance_Flamme)
Vit_Ext = Attack("Vit_Ext", 75, 5, Type.Normal)
arca.add_attack(Vit_Ext)

levia = Pokemon("Léviator", random.randint(80,120), Type.Water)
Ouragan = Attack("Ouragan", 70, 10, Type.Flying)
levia.add_attack(Ouragan)
Hydrocanon = Attack("Hydrocanon", 65, 10, Type.Water)
levia.add_attack(Hydrocanon)
levia.add_attack(Danse_Pluie)
Ultralaser = Attack("Ultralaser", 100, 5, Type.Dragon)
levia.add_attack(Ultralaser)

rhino = Pokemon("Rhinoferos", random.randint(80,120), Type.Rock)
Furie = Attack("Furie", 15, 15, Type.Normal)
rhino.add_attack(Furie)
Tempetesable = Attack("Tempetesable", 5, 25, Type.Rock)
rhino.add_attack(Tempetesable)
Eboulement = Attack("Eboulement", 20, 15, Type.Rock)
rhino.add_attack(Eboulement)
Seisme = Attack("Seisme", 45, 10, Type.Rock)
rhino.add_attack(Seisme)

alak = Pokemon("Alakazam", random.randint(80,120), Type.Psy)
Entrave = Attack("Entrave", 35, 20, Type.Psy)
alak.add_attack(Entrave)
Soin = Attack("Soin", 0, 5, Type.Buff, True)
alak.add_attack(Soin)
alak.add_attack(Psyko)
alak.add_attack(Protection)

pokemons = [pika, ronfl, menta, flori, dracau, tort, rouc, koko, arca, levia, rhino, alak]

map = Map()

game = Game(pokemons, map)

game.SpawmColletible()

while not game.close:
    game.Update()

print(color.END)