from game import *

pika = Pokemon("Pikachu", random.randint(211,274), Type.Electric)
Vive_Attaque = Attack("Vive_Attaque", 40, 30, Type.Normal)
pika.add_attack(Vive_Attaque.copy())
Eclair = Attack("Eclair", 40, 30, Type.Electric)
pika.add_attack(Eclair.copy())
Tonnerre = Attack("Tonnerre", 90, 15, Type.Electric)
pika.add_attack(Tonnerre.copy())
Fatal_Foudre = Attack("Fatal_Foudre", 110, 10, Type.Electric)
pika.add_attack(Fatal_Foudre.copy())

menta = Pokemon("Mentali", random.randint(271,334), Type.Psy)
Météores = Attack("Météores", 60, 20, Type.Rock)
menta.add_attack(Météores.copy())
Protection = Attack("Protection", 0, 20, Type.Buff, True)
menta.add_attack(Protection.copy())
Coud_Boue = Attack("Coud'Boue", 20, 10, Type.Rock)
menta.add_attack(Coud_Boue.copy())
Psyko = Attack("Psyko", 90, 10, Type.Psy)
menta.add_attack(Psyko.copy())

ronfl = Pokemon("Ronflex", random.randint(461,524), Type.Normal)
Plaquage = Attack("Plaquage", 85, 15, Type.Normal)
ronfl.add_attack(Plaquage.copy())
Repos = Attack("Repos", 0, 5, Type.Buff, True)
ronfl.add_attack(Repos.copy())
Ronflement = Attack("Ronflement", 50, 15, Type.Normal)
ronfl.add_attack(Ronflement.copy())
Amnesie = Attack("Amnesie", 40, 20, Type.Psy)
ronfl.add_attack(Amnesie.copy())

flori = Pokemon("Florizarre", random.randint(301,364), Type.Grass)
Giga_Sangsue = Attack("Giga_Sangsue", 75, 10, Type.Grass)
flori.add_attack(Giga_Sangsue.copy())
Zenith = Attack("Zenith", 50, 5, Type.Fire)
flori.add_attack(Zenith.copy())
Synthese = Attack("Synthese", 0, 5, Type.Buff)
flori.add_attack(Synthese.copy())
Lance_Soleil = Attack("Lance_Soleil", 120, 10, Type.Grass)
flori.add_attack(Lance_Soleil.copy())

dracau = Pokemon("Dracaufeu", random.randint(297,360), Type.Fire)
Cru_Aile = Attack("Cru_Aile", 60, 35, Type.Flying)
dracau.add_attack(Cru_Aile.copy())
Danseflamme = Attack("Danseflamme", 35, 15, Type.Fire)
dracau.add_attack(Danseflamme.copy())
Tranche = Attack("Tranche", 70, 20, Type.Normal)
dracau.add_attack(Tranche)
Lance_Flamme = Attack("Lance-Flamme", 100, 15, Type.Fire)
dracau.add_attack(Lance_Flamme.copy())

tort = Pokemon("Tortank", random.randint(299,362), Type.Water)
Surf = Attack("Surf", 90, 15, Type.Water)
tort.add_attack(Surf.copy())
Danse_Pluie = Attack("Danse Pluie", 0, 5, Type.Buff, True)
tort.add_attack(Danse_Pluie.copy())
Blizzard = Attack("Blizzard", 110, 5, Type.Water)
tort.add_attack(Blizzard.copy())
Siphon = Attack("Siphon", 35, 15, Type.Water)
tort.add_attack(Siphon.copy())

#////////////////////////////////////////////////////////////////////////BLUE\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

rouc = Pokemon("Roucarnage", random.randint(307,370), Type.Flying)
rouc.add_attack(Vive_Attaque.copy())
Vent_Violent = Attack("Vent_Violent", 110, 10, Type.Flying)
rouc.add_attack(Vent_Violent.copy())
rouc.add_attack(Cru_Aile.copy())
Aeropique = Attack("Aeropique", 60, 35, Type.Normal)
rouc.add_attack(Aeropique.copy())

koko = Pokemon("Noadkoko", random.randint(331,394), Type.Grass)
koko.add_attack(Zenith.copy())
koko.add_attack(Giga_Sangsue.copy())
BombOeuf = Attack("BombOeuf", 90, 10, Type.Grass)
koko.add_attack(BombOeuf.copy())
koko.add_attack(Lance_Soleil.copy())

arca = Pokemon("Arcanin", random.randint(321,384), Type.Fire)
Hurlement = Attack("Hurlement", 40, 20, Type.Normal)
arca.add_attack(Hurlement.copy())
arca.add_attack(Météores.copy())
arca.add_attack(Lance_Flamme.copy())
Vit_Ext = Attack("Vit_Ext", 80, 5, Type.Normal)
arca.add_attack(Vit_Ext.copy())

levia = Pokemon("Léviator", random.randint(331,394), Type.Water)
Ouragan = Attack("Ouragan", 40, 20, Type.Dragon)
levia.add_attack(Ouragan.copy())
Hydrocanon = Attack("Hydrocanon", 110, 5, Type.Water)
levia.add_attack(Hydrocanon.copy())
Vent_Violent = Attack("Vent_Violent", 110, 10, Type.Flying)
levia.add_attack(Vent_Violent.copy())
Ultralaser = Attack("Ultralaser", 150, 5, Type.Dragon)
levia.add_attack(Ultralaser.copy())

rhino = Pokemon("Rhinoferos", random.randint(351,414), Type.Rock)
Plaquage = Attack("Plaquage", 85, 15, Type.Normal)
rhino.add_attack(Plaquage.copy())
Tempetesable = Attack("Tempetesable", 20, 25, Type.Rock)
rhino.add_attack(Tempetesable.copy())
Eboulement = Attack("Eboulement", 75, 10, Type.Rock)
rhino.add_attack(Eboulement.copy())
Seisme = Attack("Seisme", 100, 10, Type.Rock)
rhino.add_attack(Seisme.copy())

alak = Pokemon("Alakazam", random.randint(251,314), Type.Psy)
Rafale_Psy = Attack("Rafale_Psy", 65, 20, Type.Psy)
alak.add_attack(Rafale_Psy.copy())
Facade = Attack("Facade", 70, 20, Type.Normal)
alak.add_attack(Facade.copy())
alak.add_attack(Psyko.copy())
alak.add_attack(Protection.copy())

pokemons = [pika, ronfl, menta, flori, dracau, tort, rouc, koko, arca, levia, rhino, alak]

map = Map()

game = Game(pokemons, map)

game.SpawmColletible()

while not game.close:
    game.Update()

input("")